import * as React from "react";
import { Typography, Divider } from "antd";
import GtexForm from "./GtexForm";
import CodeSnippet from "../../components/CodeSnippet/CodeSnippet";

const { Title, Paragraph } = Typography;

const markdown = `
import Client from "@tiledb-inc/tiledb-cloud";
import { Layout } from '@tiledb-inc/tiledb-cloud/v3';

const client = new Client({
    apiKey: ''
});

const ranges = [
    ["ENSG00000202059.1", "ENSG00000202059.1"],
    []
]

const query = {
    layout: Layout.RowMajor,
    ranges: ranges,
    bufferSize: 150000000,
};

(async function() {
  // Iterate over all results in case query is incomplete
  for await (let results of client.query.ReadQuery("TileDB-Inc", "gtex-analysis-rnaseqc-gene-tpm", query)) {
      console.log(results);
  }
})();
`;

const Gtex: React.FC = () => {
  return (
    <>
      <Typography>
        <Title>GTEx</Title>
        <Paragraph>
          <b>
            Store RNA-seq data generated by the Genotype-Tissue Expression
            (GTEx) project
          </b>
        </Paragraph>
        <Paragraph>
          • Original format: 56,200 gene × 17,382 sample matrix <br />• Array:
          2D sparse array with dimensions for gene_id and sample names <br />
        </Paragraph>
        <Title level={4}>Example code</Title>
      </Typography>
      <CodeSnippet>{markdown}</CodeSnippet>
      <Divider />
      <GtexForm />
    </>
  );
};

export default Gtex;
